object Version {
    const val kotlinVersion = "1.5.21"
    const val kotlinCore = "1.6.0"
    const val appCompat = "1.3.0"
    const val materialDesign = "1.4.0"
    const val constraintLayout = "1.1.3"
    const val extJunitVersion = "1.1.3"
    const val espressoCore = "3.4.0"
    const val navFragment = "2.3.5"
    const val navUi = "2.3.5"
    const val legacySupport = "4:1.0.0"
    const val roomDb = "2.3.0"
    const val coroutine = "1.5.0"
    const val lifecycleVM = "2.3.1"
    const val roomKtx = "2.3.0"
    const val retrofit = "2.9.0"
    const val moshi = "2.4.0"
    const val dagger = "2.37"
}